### ISSUE TITLE
websocket issue

### ISSUE THREAD

**Issue by tsing-01** [geralt1002/Simple-Vue-Chat#15]
![image](https://github.com/geralt1002/Simple-Vue-Chat/assets/113537150/c767f299-fe8c-40b8-9d75-60095534f554)
It have a issue after I run all project

can you help me check it out?

**Comment by geralt1002** [comment]
If you have modified the code according to the comments, try removing the lines about proxy in the vue.config.js file. If this does not help, try implementing a secure connection between the server and the client
